name: Release - NPM Publish

on:
  workflow_dispatch:

env:
  NODE_ENV: release

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish to npm
        if: github.event_name == 'workflow_dispatch'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
